### ISSUE TITLE
Limit PTR requests

### ISSUE THREAD

**Issue by beerisgood** [stoptracking/windows10#1]
Why change that setting?
(It doesn't exist by default)

Also looks like this is only for Windows 2000 and Server 2003 relevant:
https://support.microsoft.com/en-us/help/246804/how-to-enable-or-disable-dns-updates-in-windows-2000-and-in-windows-se

**Comment by asvc** [comment]
@beerisgood Thanks for checking, I haven't looked at this repository for some time.
Please feel free to "watch" it as I will be updating the materials in 2020.

Also, contributions are more than welcome.
