### ISSUE TITLE
Review/update GPOs for 20H1

### ISSUE THREAD

**Issue by asvc** [stoptracking/windows10#2]

**Comment by beerisgood** [comment]
Any updates?
@asvc 

Release is next month

**Comment by asvc** [comment]
@beerisgood , there certainly will be updates, I just don't want to push an information of dubious quality so checking things locally and carefully planning. Please stay tuned.

If you would like to collaborate -- please feel free to e-mail me.

**Comment by asvc** [comment]
Closing as outdated.
