### ISSUE TITLE
Project's future

### ISSUE THREAD

**Issue by savchenko** [stoptracking/windows10#22]
## Current state of affairs

The time has come for someone with enough of time, capacity and dedication to step-in and take over this project.

What I have started as an exercise of studying Windows OS, turned out to be a fight with the humongous beast that often acts contrary to user's interests. Personally, I would rather use open-source operating systems rather than play Don Quichotte in this battle against the MSFT.

While some of the technology implemented by MS was ahead of the time (App-V, Bitlocker, Application Guard...), the future of Windows-based computing looks rather grim to me: push all data to _the_ cloud, entrust Azure with your logs and hope that black-box ML will do the right thing.

This is not the future I want to promote nor the one that, in my opinion, would benefit end-users; irrespective of their allegiance and legal status.

That being said, I respect an effort number of people around the world have put into making Windows less about monetising hoi polloi and more about creating a friendly computing experience. Something that Microsoft is unable to achieve in its current shape and size.

## Next steps

I propose @beerisgood, @farag2 and others to take over what was done and see if they can build, integrate and remix it into something better. I have clarified the [Readme](https://github.com/stoptracking/windows10/blob/develop/README.md), please check the latest revision.

Probably converting scripts like [windows.bat](https://github.com/stoptracking/windows10/blob/develop/Scripts/windows.bat) to PowerShell and separating actions from properties would be a reasonable idea. Fortunately, this can be automated via a scripting language. For example:
1. What to be done is stored in JSON
2. Actions are written in PowerShell
3. Both can be updated independently

But this decision is up to whoever agrees to accept the baton of the next maintainer. If I could ask for one thing only &mdash; please avoid duplicated work and collaborate with others whenever possible. Projects similar to this one tend to revolve around the following areas:
1. Removing pre-installed junkware.
2. Reducing scope of data leaks.
3. Turning on "secure" features and turning off "insecure" ones.

And yet, there is a fair bit of wheel re-invention and duplicated struggle to achieve essentially the same outcomes. 

The only material competition here is between users who want to control their own computers vs Microsoft who does not want to cede such control and would rather have an ultimate command over people's machines and, as an extension of it, over the people themselves.

## Notable maintained projects

In alphabetical order:
- https://github.com/0x6d69636b/windows_hardening - Focus on security, automated provisioning of a baselines.
- https://github.com/beerisgood/Windows10_Hardening - Security over privacy, but generally a worthwhile write-up. 
- https://github.com/builtbybel/bloatbox - removal of preinstalled AppX packages. Better version of [apps.ps1](https://github.com/stoptracking/windows10/blob/develop/Scripts/apps.ps1)
- https://github.com/builtbybel/privatezilla - PS scripts wrapped in GUI. Focused on privacy (not to be confused with security).
- https://github.com/farag2/Windows-10-Sophia-Script - Well-thought "make-it-better" script, first commit in October 2018.

Ping @builtbybel and @0x6d69636b. In case you are interested - please feel free to join the conversation.

**Comment by 0x6d69636b** [comment]
Thanks for mentioning my project. :)

I'm currently focusing on audit using frameworks/benchmarks with HardeningKitty, but implementing measures has been on my to-do list for a long time. There's some cool stuff in the scripts from you guys that I'm still missing.

I'm happy to offer my support for porting to PowerShell, separating script from "data", and however else I can help.

**Comment by beerisgood** [comment]
I would also like adding https://github.com/AndyFul/Hard_Configurator
And ping @AndyFul

I would also like rename the project organisation to something like ConfigureWindows as this is what we do. It should also not only enforce removing or configuring stuff but provide a option to going the privacy or security hardening way. Maybe even with different harden levels.

**Comment by farag2** [comment]
Hello everyone! :rocket:
These are hard times but I'm back. Thanks for mentioning my project too. Actually I do not know how I can help you, because my project is not aimed at disabling telemetry or something similar. The only thing that suits your needs is [uninstalling](https://github.com/farag2/Windows-10-Sophia-Script/blob/047c93f25324e012b052bf3fad50ee838d28fd21/Sophia/PowerShell%205.1/Sophia.psm1#L7477) UWP applications written by my colleague using WPF with dynamically generated UWP apps list, both for current and all users. :trophy:

**Comment by savchenko** [comment]
As no one has stepped-up to take over the project, I am archiving it.
It will remain available on GitHub for anyone to use as they please.
